title: Colton Haller # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. Computer Science
  <br><br>
  Wright State University
  <br><br>
  <a href="https://www.linkedin.com/in/colton-haller-8051456a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
